#########################################################################
# Title:         Bizbox: ruTorrent | Post-Install | Settings           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Settings | Update settings For New Installs
  ansible.builtin.import_tasks: "new_installs.yml"
