####################################################################################
# Title:         Bizbox: ruTorrent | Post-Install | Settings | New Installs       #
# Author(s):     desimaniac                                                        #
# URL:           https://github.com/jeremiahg7/Bizbox                               #
# --                                                                               #
####################################################################################
#                   GNU General Public License v3.0                                #
####################################################################################
---
- name: Post-Install | Settings | New Installs | Update 'rtorrent.rc' config settings
  community.general.ini_file:
    path: "{{ rutorrent_paths_rtorrent_rc_location }}"
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: false
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  loop: "{{ rutorrent_config_new_installs_rutorrent_rc_settings_list }}"

- name: Post-Install | Settings | New Installs | Update 'php-local.ini' config settings
  community.general.ini_file:
    path: "{{ rutorrent_paths_php_local_ini_location }}"
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: false
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  loop: "{{ rutorrent_config_new_installs_php_local_ini_settings_list }}"

- name: Post-Install | Settings | New Installs | Import custom 'plugins.ini'
  ansible.builtin.copy:
    src: plugins.ini
    force: true
    dest: "{{ rutorrent_paths_plugins_ini_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: Post-Install | Settings | New Installs | Import custom 'nginx.conf' with htpasswd support
  ansible.builtin.copy:
    src: nginx.conf
    force: true
    dest: "{{ rutorrent_paths_nginx_conf_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
