#########################################################################
# Title:         Pre-Tasks: APT Task                                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT | Remove APT locks
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/var/lib/apt/lists/lock"
    - "/var/cache/apt/archives/lock"
    - "/var/lib/dpkg/lock"
