#########################################################################
# Title:         Pre-Tasks: Extra Variables Tasks                       #
# Author(s):     GrecoTechnology                                        #
# URL:           https://github.com/GrecoTechnology/Bizbox              #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Load user domain
  set_fact:
    user: "{{ user | combine( { 'domain': domain } ) }}"
  when: domain is defined