#########################################################################
# Title:         Pre-Tasks: Git Task                                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/GrecoTechnology/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Git | Lookup git safe directories
  ansible.builtin.shell: git config --global -l
  register: git_config
  ignore_errors: true
  when: not ('preinstall' in ansible_run_tags)

- name: Git | Set Bizbox repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /srv/git/bizbox
  when: ('preinstall' in ansible_run_tags) or (not '/srv/git/bizbox' in git_config.stdout)

- name: Git | Set bb repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /srv/git/bb
  when: ('preinstall' in ansible_run_tags) or (not '/srv/git/bb' in git_config.stdout)

- name: Git | Set Sandbox repository as safe directory
  ansible.builtin.shell: git config --global --add safe.directory /opt/sandbox
  when: ('preinstall' in ansible_run_tags) or (not '/opt/sandbox' in git_config.stdout)
