#########################################################################
# Title:         Pre-Tasks: Variables Tasks                             #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Find Bizbox roles
  ansible.builtin.shell: "find /srv/git/bizbox/roles -type d -name 'defaults'"
  register: bizbox_roles

- name: Include Bizbox role default vars
  ansible.builtin.include_vars: "{{ item }}/main.yml"
  with_items: "{{ bizbox_roles.stdout_lines }}"

- name: Sandbox
  block:

    - name: Find Sandbox roles
      ansible.builtin.shell: "find /opt/sandbox/roles -type d -name 'defaults'"
      register: sandbox_roles

    - name: Include Sandbox role default vars
      ansible.builtin.include_vars: "{{ item }}/main.yml"
      with_items: "{{ sandbox_roles.stdout_lines }}"
  when: (playbook_dir == "/opt/bizbox_mod")

- name: Check if 'localhost.yml' exists
  ansible.builtin.stat:
    path: "/srv/git/bizbox/inventories/host_vars/localhost.yml"
  register: localhost_inventory_file

- name: Import Inventory variables
  ansible.builtin.include_vars: "/srv/git/bizbox/inventories/host_vars/localhost.yml"
  when: localhost_inventory_file.stat.exists

