#########################################################################
# Title:         Bizbox: UnionFS | Basic Tasks                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Basics | Check to see if '/mnt/remote' exists"
  ansible.builtin.stat:
    path: "/mnt/remote"
  register: mnt_remote

- name: "Basics | Create '/mnt/remote' directory"
  ansible.builtin.file:
    path: "/mnt/remote"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true

  when: (not mnt_remote.stat.exists)
