#########################################################################
# Title:         Bizbox: UnionFS | MergerFS Tasks                      #
# Author(s):     EnorMOZ, desimaniac, salty                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "MergerFS | Get URL for latest mergerfs release"
  ansible.builtin.shell: "{{ mergerfs_release_lookup_command }}"
  args:
    executable: /bin/bash
    warn: false
  register: mergerfs_download_url
  ignore_errors: true

- name: "MergerFS | Uninstall mergerfs"
  ansible.builtin.apt:
    name: mergerfs
    state: absent

- name: "MergerFS | Install mergerfs"
  ansible.builtin.apt:
    deb: "{{ mergerfs_download_url.stdout | default(mergerfs_download_backup_url, true) }}"
    state: present
  register: mergerfs_install_result
  until: "mergerfs_install_result is not failed"
  retries: 5
  delay: 10

- name: "MergerFS | Import 'mergerfs.service'"
  ansible.builtin.template:
    src: mergerfs.service.j2
    dest: /etc/systemd/system/mergerfs.service
    mode: "0755"
    force: "{{ 'true' if ('mounts_override' in ansible_run_tags) else 'false' }}"

- name: Mount Path Tasks
  ansible.builtin.import_tasks: "mount_path.yml"

- name: "MergerFS | Start 'mergerfs.service'"
  ansible.builtin.systemd:
    name: mergerfs.service
    state: started
    enabled: true
    daemon_reload: true
