#########################################################################
# Title:         Bizbox: UnionFS | Mount Path Tasks                    #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Mount Path | Force unmount '/mnt/unionfs'"
  ansible.builtin.shell: "/bin/umount -f '/mnt/unionfs' 2>/dev/null || :"
  ignore_errors: true

- name: "Mount Path | Check if '/mnt/unionfs' exists"
  ansible.builtin.stat:
    path: "/mnt/unionfs"
  register: mnt_unionfs
  ignore_errors: true

- name: "Mount Path | Tasks for '/mnt/unionfs' path"
  block:

    - name: "Mount Path | Remove empty directories in '/mnt/unionfs'"
      ansible.builtin.shell: "find '/mnt/unionfs' -type d -empty -delete"
      ignore_errors: true

    - name: "Mount Path | Recursively find '/mnt/unionfs' files"
      ansible.builtin.find:
        paths: "/mnt/unionfs"
        hidden: true
        recurse: true
      register: mnt_unionfs_files

    - name: "Mount Path | Backup non-empty '/mnt/unionfs' path"
      ansible.builtin.shell: "mv /mnt/unionfs /mnt/unionfs_{{ '%Y-%m-%d_%H.%M.%S' | strftime(ansible_date_time['epoch'] | int) }}"
      ignore_errors: true
      when: (mnt_unionfs_files.matched | int > 0)

    - name: "Mount Path | Remove '/mnt/unionfs'"
      ansible.builtin.file:
        path: "/mnt/unionfs"
        state: absent

  when: (mnt_unionfs is failed) or (mnt_unionfs.stat.exists)

- name: "Mount Path | Create '/mnt/unionfs' directory"
  ansible.builtin.file:
    path: "/mnt/unionfs"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true
