#########################################################################
# Title:         Bizbox: Sanity Check | Repository Check               #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Repository | Check Current Hash
  ansible.builtin.shell: git rev-parse HEAD
  register: git_version

- name: Repository | Print Current Hash
  ansible.builtin.debug:
    msg: "Commit: {{ git_version.stdout }}"
