##########################################################################
# Title:         Sandbox: Wordpress | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/GrecoTechnology/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

wordpress_name: "{{ user.domain | replace('.','-')+'-wordpress' }}"

################################
# Paths
################################

wordpress_paths_folder: wordpress
wordpress_paths_location: "{{ server_appdata_path }}/{{ wordpress_paths_folder }}"
wordpress_paths_folders_list:
  - "{{ wordpress_paths_location }}"

################################
# Web
################################

wordpress_web_subdomain: ""
wordpress_web_domain: "{{ user.domain }}"
wordpress_web_port: "80"
wordpress_web_url: "{{ 'https://' + wordpress_web_domain
                    if (reverse_proxy_is_enabled)
                    else 'http://localhost:' + wordpress_web_port }}"

################################
# DNS
################################

wordpress_dns_record: "{{ wordpress_web_subdomain }}"
wordpress_dns_zone: "{{ wordpress_web_domain }}"
wordpress_dns_proxy: "{{ dns.proxied }}"

################################
# Mariadb
################################

mariadb_db_name: "{{ user.domain|replace('.com','') }}"

################################
# Traefik
################################

wordpress_traefik_middleware: "{{ 'wp-migration,' + traefik_default_middleware }}"
wordpress_traefik_certresolver: "{{ traefik_default_certresolver }}"
wordpress_traefik_enabled: true

################################
# Docker
################################

# Container
wordpress_docker_container: "{{ wordpress_name }}"

# Image
wordpress_docker_image_pull: true
wordpress_docker_image_tag: "latest"
wordpress_docker_image: "wordpress:{{ wordpress_docker_image_tag }}"

# Ports
wordpress_docker_ports_defaults:
  - "{{ wordpress_web_port }}"
wordpress_docker_ports_custom: []
wordpress_docker_ports: "{{ wordpress_docker_ports_defaults
                            + wordpress_docker_ports_custom
                         if (not reverse_proxy_is_enabled)
                         else wordpress_docker_ports_custom }}"

# Envs
wordpress_docker_envs_default:
  TZ: "{{ tz }}"
  WORDPRESS_DB_HOST: "{{ user.domain | replace('.','-')+'-mariadb' }}"
  WORDPRESS_DB_USER: "root"
  WORDPRESS_DB_PASSWORD: "password321"
  WORDPRESS_DB_NAME: "{{ mariadb_db_name }}"
wordpress_docker_envs_custom: {}
wordpress_docker_envs: "{{ wordpress_docker_envs_default
                           | combine(wordpress_docker_envs_custom) }}"

# Commands
wordpress_docker_commands_default: []
wordpress_docker_commands_custom: []
wordpress_docker_commands: "{{ wordpress_docker_commands_default
                               + wordpress_docker_commands_custom }}"

# Volumes
wordpress_docker_volumes_default:
  - "{{ wordpress_paths_location }}:/var/www/html"
wordpress_docker_volumes_custom: []
wordpress_docker_volumes: "{{ wordpress_docker_volumes_default
                              + wordpress_docker_volumes_custom }}"

# Devices
wordpress_docker_devices_default: []
wordpress_docker_devices_custom: []
wordpress_docker_devices: "{{ wordpress_docker_devices_default
                              + wordpress_docker_devices_custom }}"

# Hosts
wordpress_docker_hosts_default: []
wordpress_docker_hosts_custom: []
wordpress_docker_hosts: "{{ docker_hosts_common
                            | combine(wordpress_docker_hosts_default)
                            | combine(wordpress_docker_hosts_custom) }}"

# Labels
wordpress_docker_labels_default: {}
wordpress_docker_labels_custom:
  traefik.http.routers.wordpress-http.entrypoints: web
  traefik.http.routers.wordpress-http.rule: "Host(`{{ user.domain }}`)"
  traefik.http.routers.wordpress.entrypoints: websecure
  traefik.http.routers.wordpress.rule: "Host(`{{ user.domain }}`)"
  traefik.http.middlewares.wp-migration.headers.contentSecurityPolicy: "script-src 'self' 'sha256-rBhJWgLTI5geQ9XiTXf3JBDaj8+M6nd4EH/1WzTlbJI=' 'sha256-hQDpYiHfZXE14eE4y2m45R9t4PkR0vald7i1qNpgQm8=' 'sha256-RPiI+PA1EhKvMw4fF+bgtfSuOePiRT78ovT0mPRd+IQ=' 'sha256-4LIggHk3u7VSFxLgGBH9q/eTAGH8Nqm0QhRvtg1IDlU=' 'sha256-bOHm3jJRjBtOybGrbc7HXXV57Qp8VFC65nGoNACf2EY=' 'sha256-fZIx1ukK+dEJq5T+5M6mayzaPFubN/b85dpdRL7Xwq4=' 'sha256-7+Cai1EhQOt360NzDf0sNdEZ0o2ysQRr6D47MqFd3Mg=' 'sha256-8//zSBdstORCAlBMo1/Cig3gKc7QlPCh9QfWbRu0OjU=' 'sha256-4Iwf2dEl6VGbpkcB/OW7Z5TXT2gOGdkN22VJpM9PwL4=' 'sha256-X/OEkZ/ytkcEbDTUKiyG6q4kvS52ashH/ro1R8MGLa0=' 'sha256-zwGmIUR+Z6gWKbwoJ2Z3yGxI/XLETLqDqCRIV0qt/WA=' 'sha256-HV4D0kIF+EVIO56QJByRpxq5X8TAkP4KjfX2cijcs3Y=' 'sha256-60Y5SZryMP/67Q/k36LVBXH6SBee31fcbdC5y8D7RYw=' 'unsafe-eval';"

wordpress_docker_labels: "{{ docker_labels_common
                             | combine(wordpress_docker_labels_default)
                             | combine(wordpress_docker_labels_custom) }}"

# Hostname
wordpress_docker_hostname: "{{ wordpress_web_domain }}"

# Networks
wordpress_docker_networks_alias: "{{ wordpress_name }}"
wordpress_docker_networks_default: []
wordpress_docker_networks_custom: []
wordpress_docker_networks: "{{ docker_networks_common
                               + wordpress_docker_networks_default
                               + wordpress_docker_networks_custom }}"

# Capabilities
wordpress_docker_capabilities_default: []
wordpress_docker_capabilities_custom: []
wordpress_docker_capabilities: "{{ wordpress_docker_capabilities_default
                                   + wordpress_docker_capabilities_custom }}"

# Security Opts
wordpress_docker_security_opts_default: []
wordpress_docker_security_opts_custom: []
wordpress_docker_security_opts: "{{ wordpress_docker_security_opts_default
                                    + wordpress_docker_security_opts_custom }}"

# Restart Policy
wordpress_docker_restart_policy: unless-stopped

# State
wordpress_docker_state: started
