#########################################################################
# Title:         Bizbox: Jellyfin - Settings Tasks                     #
# Author(s):     kowalski, desimaniac, owine                            #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Restart Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/restart_docker_container.yml"

- name: Post-Install | Wait for 'system.xml' file to be created
  ansible.builtin.wait_for:
    path: "{{ jellyfin_paths_sys_xml_location }}"
    state: present

- name: Post-Install | Wait for 'network.xml' file to be created
  ansible.builtin.wait_for:
    path: "{{ jellyfin_paths_net_xml_location }}"
    state: present

- name: Stop Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"

- name: Settings | Update 'system.xml' file
  community.general.xml:
    path: "{{ jellyfin_paths_sys_xml_location }}"
    xpath: "/ServerConfiguration/{{ item.xpath }}"
    value: "{{ item.value }}"
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ jellyfin_system_settings_list }}"

- name: Settings | Update 'network.xml' file
  community.general.xml:
    path: "{{ jellyfin_paths_net_xml_location }}"
    xpath: "/NetworkConfiguration/{{ item.xpath }}"
    value: "{{ item.value }}"
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ jellyfin_network_settings_list }}"

- name: Start Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
