############################################################################
# Title:            Bizbox: Mariadb Backup                                 #
# Author(s):        btmarouane                                             #
# URL:              https://github.com/GrecoTechnology/Bizbox              #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create db backup
  shell: mysqldump --column-statistics=0 -h {{ DB_HOST }} -u {{ DB_USER }} -p{{ DB_PASSWORD }} {{ DB_NAME }} > {{ mariadb_backup_path }}/{{ app }}.sql
