#########################################################################
# Title:         Bizbox: Overseerr Role                                #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Overseerr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    overseerr_name: "{{ role }}"
  with_items: "{{ overseerr_instances }}"
  loop_control:
    loop_var: role
