#########################################################################
# Title:         Bizbox: Diun Role                                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Import default config
  ansible.builtin.copy:
    src: "diun.yml"
    dest: "{{ diun_paths_location }}/diun.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: false

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
