#########################################################################
# Title:         Bizbox: Cloudflare | Page Rules | Add Page Rule       #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Page Rules | Add Page Rule | Add Cloudflare Page Rule for Lets Encrypt
  ansible.builtin.uri:
    url: 'https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone }}/pagerules'
    method: POST
    headers:
      X-Auth-Email: '{{ cloudflare.email }}'
      X-Auth-Key: '{{ cloudflare.api }}'
    body_format: json
    body:
      priority: 10
      status: active
      targets:
        - target: url
          constraint:
            operator: matches
            value: "*{{ fld.stdout }}/.well-known/acme-challenge/*"
      actions:
        - id: browser_check
          value: 'off'
    status_code: 200,400
  register: cf_page_rule_creation

- name: Page Rules | Add Page Rule | Print result of Cloudflare Page Rule Creation
  ansible.builtin.debug:
    msg: "Successfully created Let's Encrypt Cloudflare page rule for '{{ fld.stdout }}'"
  when: (cf_page_rule_creation.json.success is defined) and (cf_page_rule_creation.json.success)
