#########################################################################
# Title:         Bizbox: User Role                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: User Account
  ansible.builtin.import_tasks: "subtasks/user_account.yml"
