##########################################################################
# Title:         Uninstall  | Default Variables                          #
# Author(s):     btmarouane                                              #
# URL:           https://github.com/GrecoTechnology/Bizbox               #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Get list of apps' subfolders
  block:
    - name: Get list of apps' subfolders | Get apps
      ansible.builtin.find:
        paths: "{{ server_appdata_path }}"
        file_type: directory
        recurse: false
      register: apps

    - name: Set apps names
      set_fact:
        apps: "{{apps.files}}"
  when: all is defined and all == 'true'

- name: Print apps names
  ansible.builtin.debug:
    var: apps

- name: Remove apps
  include_tasks: subtasks/uninstall_app.yml
  with_items: "{{ apps|map(attribute='path')|map('basename')|list }}"

- name: Remove domain folder
  ansible.builtin.file:
    path: "{{ server_appdata_path }}"
    state: absent
  when: all is defined and all == 'true'