##########################################################################
# Title:         Uninstall  | Default Variables                          #
# Author(s):     btmarouane                                              #
# URL:           https://github.com/GrecoTechnology/Bizbox               #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Get list of apps' subfolders
  ansible.builtin.find:
    paths: "{{ server_appdata_path }}"
    file_type: directory
    recurse: true
  register: apps
  when: all is defined and all == 'true'

- name: Set apps names
  set_fact:
    apps: apps.files

- name: Print apps names
  ansible.builtin.debug:
    vars: apps

- name: Remove apps
  include_tasks: subtasks/uninstall_app.yml
  with_items: "{{ apps.split(',') }}"
