#########################################################################
# Title:         Bizbox: Reinstall Role                                 #
# Author(s):     btmarouane                                             #
# URL:           https://github.com/GrecoTechnology/Bizbox              #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

utils_apps: ['redis', 'mariadb', 'authelia']
