#########################################################################
# Title:         Bizbox: Reinstall Role                                 #
# Author(s):     btmarouane                                             #
# URL:           https://github.com/GrecoTechnology/Bizbox              #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

reinstall_docker_container: "{{ user.domain | replace('.','-')+'-'+app }}"
util_apps: ['mariadb']
uninstall_task_path: "/srv/git/bizbox/roles/uninstall/tasks/subtasks/uninstall_app.yml"
