#########################################################################
# Title:            Sandbox: WordPress                                  #
# Author(s):        Migz93, salty                                       #
# URL:              https://github.com/GrecoTechnology/Sandbox          #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check Docker Container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/check_docker_container.yml"
  vars:
    container_name: "{{ user.domain | replace('.','-')+'-mariadb' }}"
  register: result

- name: Redis Role
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_name: "{{redis_name}}"
    redis_paths_location: "{{redis_name}}"

- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb
  when: not result.exists

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: MariaDB | Create wordpress database
  community.mysql.mysql_db:
    name: "{{ mariadb_db_name }}"
    login_host: "{{ user.domain | replace('.','-')+'-mariadb' }}"
    login_user: "root"
    login_password: "{{ mariadb_docker_envs_mysql_root_password }}"
    state: present

- name: "Settings | env tasks"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/env/env.yml"

- name: "Settings | Http Headers tasks"
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/traefik/configure_http_headers.yml"

- name: "Settings | Htaccess tasks"
  ansible.builtin.include_tasks: subtasks/configure_htaccess.yml

- name: "Settings | uploads.ini tasks"
  template:
    src: templates/uploads.ini.j2
    dest: "{{wordpress_config_path}}/uploads.ini"
    owner: "{{user.name}}"
    group: "{{user.name}}"
    mode: "0775"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Configure Internal Apache SSL
  ansible.builtin.include_tasks: subtasks/configure_ssl.yml
  vars:
    certdir: "{{wordpress_config_ssl_path}}"
    subject_alt_name: "DNS:{{user.domain}},IP:{{ip_address_public}},IP:127.0.0.1"
    common_name: "{{user.domain}}"
    passphrase_file: "{{ root_certdir }}/passphrase.txt"
    default_ssl_conf_src_path: templates/default-ssl.conf.default.j2
    default_ssl_conf_dest_path: "{{wordpress_config_ssl_path}}/default-ssl.conf"

- name: Restart Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/restart_docker_container.yml"
