##################################################################################
# Title:         Bizbox: Resources | Tasks | Directories | Create Directories   #
# Author(s):     salty                                                           #
# URL:           https://github.com/jeremiahg7/Bizbox                             #
# --                                                                             #
##################################################################################
#                   GNU General Public License v3.0                              #
##################################################################################
---
- name: Resources | Tasks | Directories | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list')
                  + lookup('vars', role_name + '_paths_folders_list_custom', default=[]) }}"
