##################################################################################
# Title:         Bizbox: Resources | Tasks | Directories | Create Directories   #
# Author(s):     salty                                                           #
# URL:           https://github.com/GrecoTechnology/Bizbox                             #
# --                                                                             #
##################################################################################
#                   GNU General Public License v3.0                              #
##################################################################################
---
- name: "Settings | env tasks | Set '_var_prefix' variable"
  ansible.builtin.set_fact:
    _var_prefix: "{{ var_prefix
                  if (var_prefix is defined)
                  else role_name }}"

- name: Resources | Tasks | Directories | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', _var_prefix + '_paths_folders_list')
                  + lookup('vars', _var_prefix + '_paths_folders_list_custom', default=[]) }}"
