############################################################################
# Title:            Bizbox: Uninstall | Uninstall apps Task                #
# Author(s):        btmarouane                                             #
# URL:              https://github.com/GrecoTechnology/Bizbox              #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Remove apps | Remove containers
  block:
  - ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
    vars:
      uninstall_docker_container: "{{ user.domain | replace('.','-')+'-'+app }}"

  - name: Remove apps | Remove containers | Remove invoiceninjav5 nginx container
    ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
    vars:
      uninstall_docker_container: "{{ user.domain | replace('.','-')+'-'+app+'-nginx' }}"
    when: app == "invoiceninjav5"

  - name: Remove apps | Remove containers | Remove wordpress redis container
    ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
    vars:
      uninstall_docker_container: "{{ user.domain | replace('.','-')+'-'+app+'-redis' }}"
    when: app == "wordpress"

  - name: Remove apps | Remove containers | Remove traefik redis and authelia containers
    ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
    vars:
      uninstall_docker_container: "{{ user.domain | replace('.','-')+'-'+traefik_item }}"
    with_items:
      - redis
      - authelia
    loop_control:
      loop_var: traefik_item
    when: app == "traefik"

  - name: Remove apps | Remove db
    mysql_db:
      name: "{{ app }}"
      state: absent
      login_host: "{{ mariadb_docker_container }}"
      login_user: "{{ root_user }}"
      login_password: "{{ root_password }}"
    ignore_errors: true
    when: all is defined and all == 'false'

- name: Remove apps | Remove files
  block:
  - name: Remove apps | Remove files | Remove appdata files
    ansible.builtin.file:
      path: "{{ server_appdata_path }}/{{ app }}"
      state: absent

- name: Remove apps | Remove files | Remove traefik redis and authelia appdata files
  ansible.builtin.file:
    path: "{{ server_appdata_path }}/{{ traefik_item }}"
    state: absent
  with_items:
    - redis
    - authelia
  loop_control:
    loop_var: traefik_item
  when: app == "traefik"

- name: Remove apps | Remove files | Remove http_headers.yml file
  ansible.builtin.file:
    path: "{{ traefik_path_http_headers_config_location }}/{{ user.domain | replace('.','-')+'-'+app+'-http-headers.yml' }}"
    state: absent

- name: Remove apps | Remove files | Remove traefik config
  ansible.builtin.file:
    path: "/opt/traefik"
    state: absent
  when: app == "traefik"

- name: Remove apps | Update domain.tld.env.yml
  block:
  - name: Remove apps | Update domain.tld.env.yml | Delete role env config
    ansible.builtin.shell: |
      yyq e 'del(.{{app}})' {{server_domain_env_path}}
    register: updated_domain_env_config
  - name: Remove apps | Update domain.tld.env.yml
    block:
      - copy:
          dest: "{{ server_domain_env_path }}"
          content: ""
          owner: "{{ user.name }}"
          group: "{{ user.name }}"
          mode: 0775
          force: true
        when: updated_domain_env_config.stdout == '{}'
      - copy:
          dest: "{{ server_domain_env_path }}"
          content: "{{updated_domain_env_config.stdout}}\n"
          owner: "{{ user.name }}"
          group: "{{ user.name }}"
          mode: 0775
          force: true
        when: updated_domain_env_config.stdout != '{}'
