#########################################################################
# Title:         Bizbox: NZBHydra2 | Settings Task                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Settings | Wait for config file to be created
  ansible.builtin.wait_for:
    path: "{{ nzbhydra2_paths_config_location }}"
    state: present
    timeout: 15

- name: Post-Install | Settings | Stop container
  community.docker.docker_container:
    name: "{{ nzbhydra2_docker_container }}"
    container_default_behavior: compatibility
    tls_hostname: localhost
    state: stopped

- name: Post-Install | Settings | Update settings
  ansible.builtin.shell: |
    yyq e -i '{{ item }}' {{ nzbhydra2_paths_config_location }}
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ nzbhydra2_config_settings_list }}"

- name: Post-Install | Settings | Start container
  community.docker.docker_container:
    name: "{{ nzbhydra2_docker_container }}"
    container_default_behavior: compatibility
    tls_hostname: localhost
    state: "{{ nzbhydra2_docker_state }}"
