##########################################################################
# Title:         Bizbox: Plex | Post-Install Tasks                      #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/jeremiahg7/Bizbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
# Sometimes docker will set transcodes folder to root after a restore.
- name: Post-Install | Ensure transcodes folder has the correct permissions
  ansible.builtin.file:
    path: "{{ plex_paths_transcodes_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    recurse: true

- name: Post-Install | Update ports in '{{ plex_paths_config_location | basename }}'
  ansible.builtin.import_tasks: update_ports.yml
