#########################################################################
# Title:            Bizbox: NZBThrottle                                #
# Author(s):        desimaniac                                          #
# URL:              https://github.com/jeremiahg7/Bizbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Pre-Install Tasks
  ansible.builtin.include_tasks: "subtasks/pre-install.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
