#########################################################################
# Title:         Bizbox: Deluge | Pre-Install Tasks                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Get next available port within the range of '58112-58132' # noqa fqcn[action]
  find_next_open_port:
    low_bound: 58112
    high_bound: 58132
  register: port_lookup_58112
  ignore_errors: true
