##########################################################################
# Title:         Bizbox: Radarr | Post-Install | Update Ports           #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/jeremiahg7/Bizbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Post-Install | Update Ports | Wait for '{{ radarr_paths_config_location | basename }}' to be created
  ansible.builtin.wait_for:
    path: "{{ radarr_paths_config_location }}"
    state: present

- name: Post-Install | Update Ports | Find external port binding for '{{ radarr_docker_container }}' docker port '{{ radarr_web_port }}'
  block:

    - name: Post-Install | Update Ports | Lookup host port mapped to '{{ radarr_docker_container }}' docker port '{{ radarr_web_port }}'
      ansible.builtin.shell:
        docker port {{ radarr_docker_container }} {{ radarr_web_port }} 2> /dev/null | sed 's/[0-9.]*://'
      register: radarr_docker_port_lookup_cmd
      changed_when: false

    - name: Post-Install | Update Ports | Set port variable
      ansible.builtin.set_fact:
        radarr_docker_port_lookup: >-
          {{ (radarr_docker_port_lookup_cmd.stdout | trim)
              if (radarr_docker_port_lookup_cmd.stdout | trim | length > 0)
              else radarr_web_port }}

  when: not reverse_proxy_is_enabled

- name: Post-Install | Update Ports | Update 'Port' in '{{ radarr_paths_config_location | basename }}'
  community.general.xml:
    path: "{{ radarr_paths_config_location }}"
    xpath: /Config/Port
    value: "{{ radarr_docker_port_lookup | default(radarr_web_port) }}"
    state: present
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
  register: radarr_port_update

- name: Post-Install | Update Ports | Reset permissions of '{{ radarr_paths_config_location | basename }}'
  ansible.builtin.file:
    path: "{{ radarr_paths_config_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: radarr_port_update is changed
