############################################################################
# Title:            Bizbox: Clone | Clone app Task                         #
# Author(s):        btmarouane                                             #
# URL:              https://github.com/GrecoTechnology/Bizbox              #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Clone app | Copy data
  synchronize:
    src: "{{ clone_data_path }}"
    dest: "{{ lookup('vars', app + '_data_path') }}"
    delete: true
    recursive: true

- name: Clone app | Copy configuration
  block:
    - name: Clone app | Copy configuration | Copy http headers file
      copy:
        src: "{{clone_http_headers_path}}"
        dest: "{{ lookup('vars', app + '_config_path') }}"
        follow: yes
    - name: Clone app | Copy configuration | Configure http headers file
      block:
      - lineinfile:
          path: "{{ lookup('vars', app + '_config_path') }}/http_headers.yml"
          regexp: "{{ clone_name }}"
          line: "{{ lookup('vars', app + '_name') }}"
      - lineinfile:
          path: "{{ lookup('vars', app + '_config_path') }}/http_headers.yml"
          regexp: "{{ src_domain }}"
          line: "{{ user.domain }}"

- name: Clone app | Backup database
  ansible.builtin.include_role:
    name: mariadb_backup
  vars:
    user:
      domain: "{{ src_domain }}"

- name: Clone app | Import database
  ansible.builtin.import_tasks: import_db.yml
