############################################################################
# Title:            Bizbox: Clone | Import db Task                         #
# Author(s):        btmarouane                                             #
# URL:              https://github.com/GrecoTechnology/Bizbox              #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Import db
  mysql_db:
    name: "{{ DB_NAME }}"
    state: import
    target: "{{ BACKUP_PATH }}"
    login_host: "{{ DB_HOST }}"
    login_user: "{{ DB_USER }}"
    login_password: "{{ DB_PASSWORD }}"

- name: Update db
  mysql_query:
    login_db: "{{ DB_NAME }}"
    login_host: "{{ DB_HOST }}"
    login_user: "{{ DB_USER }}"
    login_password: "{{ DB_PASSWORD }}"
    query: UPDATE wp_options SET option_value = https://{{ lookup('vars', app + '_web_url') }}  WHERE option_name = 'home' OR option_name = 'siteurl';
  when: app == wordpress