#########################################################################
# Title:         Bizbox: Sandbox Role                                  #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create Sandbox directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: true
  with_items:
    - /opt/sandbox

- name: Clone Sandbox repo 'HEAD'
  ansible.builtin.git:
    repo: https://github.com/jeremiahg7/sandbox.git
    dest: /opt/sandbox
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
  register: sandbox_clone_status

- name: Clone Sandbox repo 'master'
  ansible.builtin.git:
    repo: https://github.com/jeremiahg7/sandbox.git
    dest: /opt/sandbox
    clone: true
    version: master
    force: true
  become: true
  become_user: "{{ user.name }}"
  when: sandbox_clone_status is failed

- name: Import default files when missing
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/sandbox/{{ (item | basename | splitext)[0] }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: false
  with_fileglob:
    - /opt/sandbox/defaults/*.*

- name: Force overwrite Sandbox ansible.cfg
  ansible.builtin.copy:
    src: "/opt/sandbox/defaults/ansible.cfg.default"
    dest: "/opt/sandbox/ansible.cfg"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: true

- name: Activate Git Hooks
  ansible.builtin.shell: bash /opt/sandbox/bin/git/init-hooks
  args:
    chdir: "/opt/sandbox"
