##########################################################################
# Title:         Bizbox: Backup | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/jeremiahg7/Bizbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
backup2_ignore_containers: []
backup2_user_defined_files: []
backup2_async_batch_size: 99
