#########################################################################
# Title:         Bizbox: Deluge | Post-Install Tasks                   #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config to be created
  ansible.builtin.wait_for:
    path: "{{ deluge_paths_conf }}"
    state: present

- name: Post-Install | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Post-Install | Stop container
  community.docker.docker_container:
    name: "{{ deluge_docker_container }}"
    container_default_behavior: compatibility
    tls_hostname: localhost
    state: stopped

- name: Post-Install | Settings Task
  ansible.builtin.import_tasks: "settings/main.yml"

- name: Post-Install | Start container
  community.docker.docker_container:
    name: "{{ deluge_docker_container }}"
    container_default_behavior: compatibility
    tls_hostname: localhost
    state: "{{ deluge_docker_state }}"
