#########################################################################
# Title:         Bizbox: iperf3 | Default Variables                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
iperf3_git_repo_url: "https://github.com/esnet/iperf.git"

iperf3_git_repo_dest: "/var/tmp/iperf3"

iperf3_binary_build_command: |
  export LD_RUN_PATH=/usr/local/lib
  cd {{ iperf3_git_repo_dest }}
  ./configure
  make
  make install
  ldconfig
  rm -rf {{ iperf3_git_repo_dest }}
iperf3_binary_path: /usr/local/bin/iperf3

iperf3_binary_version_lookup_command: |
  {{ iperf3_binary_path }} --version \
      | head -n 1 | awk '{ print $2 }'
