#########################################################################
# Title:         Bizbox: System | APT Tasks                            #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT | Set env variables
  ansible.builtin.set_fact:
    env_vars:
      DEBIAN_FRONTEND: noninteractive
      DEBIAN_PRIORITY: critical

- name: APT | Fix any potential dpkg issues
  ansible.builtin.shell: dpkg --configure --pending

- name: APT | Kill existing apt and apt-get
  ansible.builtin.shell: "killall apt apt-get >/dev/null 2>&1 || :"
  ignore_errors: true

- name: APT | Fix any potential apt issues
  ansible.builtin.shell: apt-get install --fix-broken --quiet --yes
  args:
    warn: false
  environment: "{{ env_vars }}"
  ignore_errors: true

- name: APT | Install required packages
  ansible.builtin.apt:
    state: present
    name:
      - apt-utils
      - byobu

- name: APT | APT update
  ansible.builtin.apt:
    update_cache: true
  ignore_errors: true

# https://serverfault.com/a/839563
# https://raymii.org/s/tutorials/Silent-automatic-apt-get-upgrade.html
- name: APT | APT full-upgrade
  ansible.builtin.shell: apt-get full-upgrade --quiet --yes --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  environment: "{{ env_vars }}"
  args:
    warn: false
  when: not continuous_integration
  ignore_errors: true

- name: APT | Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  ignore_errors: true

- name: APT | Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  ignore_errors: true
