#########################################################################
# Title:         Bizbox: System | Remove CPU Power Tasks               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove CPU Power | Check if 'cpupower.service' exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/cpupower.service"
  register: cpupower_service

- name: Remove CPU Power | Stop and disable 'cpupower.service'
  ansible.builtin.systemd:
    name: cpupower
    state: stopped
    enabled: false
    daemon_reload: true
  ignore_errors: true
  when: cpupower_service.stat.exists

- name: Remove CPU Power | Delete 'cpupower.service'
  ansible.builtin.file:
    path: /etc/systemd/system/cpupower.service
    state: absent
  when: cpupower_service.stat.exists
