#########################################################################
# Title:         Bizbox: System | Time Zone Tasks                      #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
# https://github.com/galexrt/ansible-timezone/blob/master/tasks/timedatectl.yml
---
- name: Get timedatectl information
  ansible.builtin.command: timedatectl
  register: timedatectl
  ignore_errors: true

- name: Get timezone list
  ansible.builtin.command: timedatectl list-timezones --no-pager
  register: timezone_list
  changed_when: false

- name: Time Zone | Fetch Time Zone if set to 'auto'
  block:

    - name: Time Zone | Get Time Zone from 'http://ip-api.com'
      ansible.builtin.uri:
        url: http://ip-api.com/line?fields=timezone
        return_content: true
      register: ip_api_timezone_response

    - name: Time Zone | Set 'timezone' variable from 'http://ip-api.com'
      ansible.builtin.set_fact:
        timezone: "{{ ip_api_timezone_response.content | trim }}"
      when:
        - (ip_api_timezone_response is succeeded)
        - (ip_api_timezone_response.content | trim | length > 0)

  when:
    - (system is defined)
    - (system.timezone is defined)
    - ('auto' in system.timezone | lower)
  ignore_errors: true

- name: Check if timezone is valid
  ansible.builtin.fail:
    msg: "Invalid timezone given, given timezone was {{ timezone }}\"."
  when: timezone_list.stdout is defined and timezone not in timezone_list.stdout

- name: Set timezone
  ansible.builtin.shell: "timedatectl set-timezone {{ timezone }}; timedatectl"
  register: timedatectl_utc
  changed_when: "timedatectl_utc.stdout is defined and 'Time zone: UTC' in timedatectl_utc.stdout"
  when: "timedatectl.stdout is defined and 'Time zone: UTC' not in timedatectl.stdout"

- name: Set hardware clock to use or not use local RTC
  ansible.builtin.shell: "timedatectl set-local-rtc {% if timezone_use_local_rtc %}1{% else %}0{% endif %} && timedatectl || true"
  register: timedatectl_rtc
  changed_when: "timedatectl_rtc.stdout is defined and 'RTC in local TZ: {% if timezone_use_local_rtc %}yes{% else %}no{% endif %}' in timedatectl_rtc.stdout"
  when: "timedatectl_rtc.stdout is defined and timezone_use_local_rtc and 'RTC in local TZ: no' not in timedatectl_rtc.stdout"
