#####################################################################################
# Title:         Bizbox: Resources | Tasks | systemd | Update Service Credentials  #
# Author(s):     desimaniac                                                         #
# URL:           https://github.com/jeremiahg7/Bizbox                                #
# --                                                                                #
#####################################################################################
#                   GNU General Public License v3.0                                 #
#####################################################################################
---
- name: Resources | Tasks | systemd | Update Service Credentials | set '_service_file' variable
  ansible.builtin.set_fact:
    _service_file: "{{ _service_name }}.service"

- name: Resources | Tasks | systemd | Update Service Credentials | set '_service_path' variable
  ansible.builtin.set_fact:
    _service_path: "/etc/systemd/system/{{ _service_file }}"

- name: Resources | Tasks | systemd | Update Service Credentials | check if '{{ _service_file }}' exists
  ansible.builtin.stat:
    path: "{{ _service_path }}"
  register: service_status

- name: Resources | Tasks | systemd | Update Service Credentials | existing '{{ _service_file }}' tasks
  block:

    - name: Resources | Tasks | systemd | Update Service Credentials | update credentials in '{{ _service_file }}'
      community.general.ini_file:
        path: "{{ _service_path }}"
        section: Service
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        state: present
        mode: '0755'
        no_extra_spaces: true
      loop:
        - { option: 'User', value: "{{ user.name }}" }
        - { option: 'Group', value: "{{ user.name }}" }
      register: credentials_state

    - name: Resources | Tasks | systemd | Update Service Credentials | systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: yes
      when: credentials_state is changed

  when: service_status.stat.exists
