#########################################################################
# Title:         Bizbox: Rclone - Preinstall Tasks                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Preinstall | Display message when kernel has been updated"
  ansible.builtin.debug:
    msg: "Kernel was updated."
  when: (preinstall_kernel_restart is defined) and (preinstall_kernel_restart)

- name: "Preinstall | Bizbox pre-install has completed!"
  ansible.builtin.debug:
    msg: "Bizbox pre-install has completed!"

- name: Preinstall | Tasks for kernel restart
  block:

    - name: "Preinstall | Display message when restarting server"
      ansible.builtin.debug:
        msg: "Restarting the server to apply changes..."

    - name: "Preinstall | Reboot"
      ansible.builtin.shell: reboot

    - name: "Preinstall | Reboot Manually"
      ansible.builtin.debug:
        msg:
          - "Failed to reboot automatically."
          - "You will need to restart the server yourself for changes to take effect."

  when: (preinstall_kernel_restart is defined) and (preinstall_kernel_restart)
