#########################################################################
# Title:         Bizbox: Docker | Binary Tasks 2                       #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Release '{{ vars[item ~ '_dpkg'] }}' from hold
  ansible.builtin.dpkg_selections:
    name: "{{ vars[item ~ '_dpkg'] }}"
    selection: install

- name: Binary | Install '{{ lookup('vars', item + '_package') }}'
  ansible.builtin.apt:
    name: "{{ lookup('vars', item + '_package') }}"
    state: "{{ docker_package_state }}"
    update_cache: true

- name: Binary | Put '{{ vars[item ~ '_dpkg'] }}' into hold
  ansible.builtin.dpkg_selections:
    name: "{{ vars[item ~ '_dpkg'] }}"
    selection: hold
  when: put_docker_dpkg_into_hold

- name: Binary | Get '{{ vars[item ~ '_name'] }}' version
  ansible.builtin.shell: "{{ vars[item ~ '_filepath'] }} --version | head -n 1 | awk '{ print $3 }' | sed 's/,$//'"
  register: binary_version
  ignore_errors: true
  changed_when: false

- name: Binary | Display '{{ vars[item ~ '_name'] }}' version
  ansible.builtin.debug:
    msg: "{{ vars[item ~ '_name'] }} version {{ binary_version.stdout }} installed."
  when: binary_version is defined
