#########################################################################
# Title:         Bizbox: Docker | Binary Tasks                         #
# Author(s):     desimaniac, l3uddz, salty                              #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Remove old official repository entry
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo_url_old }}"
    filename: "{{ docker_apt_repo_filename }}"
    update_cache: true
    state: absent

- name: Binary | Add official gpg signing key to keyring
  ansible.builtin.apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"
    keyring: /usr/share/keyrings/docker.gpg
  register: result
  retries: "{{ '0' if (not continuous_integration) else '5' }}"
  delay: 10
  until: result is succeeded

- name: Binary | Add official repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    filename: "{{ docker_apt_repo_filename }}"
    update_cache: true
  register: result
  retries: "{{ '0' if (not continuous_integration) else '5' }}"
  delay: 10
  until: result is succeeded

- name: Binary | Install Docker binaries
  ansible.builtin.include_tasks: "binary2.yml"
  loop:
    - 'containerd_io'
    - 'docker_ce'
    - 'docker_ce_cli'
