#########################################################################
# Title:            Bizbox: qBittorrent                                #
# Author(s):        Kalroth, salty                                      #
# URL:              https://github.com/jeremiahg7/Bizbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Check if existing config file exists
  ansible.builtin.stat:
    path: "{{ qbittorrent_paths_conf }}"
  register: qbittorrent_paths_conf_stat

- name: Pre-Install Tasks
  ansible.builtin.import_tasks: "subtasks/pre-install/main.yml"
  when: not continuous_integration

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Post-Install Tasks
  ansible.builtin.import_tasks: "subtasks/post-install/main.yml"
  when: (not continuous_integration) and (not qbittorrent_paths_conf_stat.stat.exists)
