####################################################################################
# Title:         Bizbox: ruTorrent | Pre-Install | Settings | Existing Installs   #
# Author(s):     desimaniac                                                        #
# URL:           https://github.com/jeremiahg7/Bizbox                               #
# --                                                                               #
####################################################################################
#                   GNU General Public License v3.0                                #
####################################################################################
---
- name: Pre-Install | Settings | Existing Installs | Update 'rtorrent.rc' config settings
  community.general.ini_file:
    path: "{{ rutorrent_paths_rtorrent_rc_location }}"
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: false
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  loop: "{{ rutorrent_config_existing_installs_rutorrent_rc_settings_list }}"

- name: Pre-Install | Settings | Existing Installs | Import custom 'nginx.conf' with htpasswd support
  ansible.builtin.copy:
    src: nginx.conf
    force: true
    dest: "{{ rutorrent_paths_nginx_conf_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
