#########################################################################
# Title:         Bizbox: ruTorrent | Pre-Install Tasks                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Remove existing 'config.php'
  ansible.builtin.file:
    path: "{{ rutorrent_paths_config_php_location }}"
    state: absent

- name: Pre-Install | Get next available port within the range of '51413-51423' # noqa fqcn[action]
  find_next_open_port:
    low_bound: 51413
    high_bound: 51423
  register: port_lookup_51413
  ignore_errors: true

- name: Pre-Install | Get next available port within the range of '6881-6891' # noqa fqcn[action]
  find_next_open_port:
    low_bound: 6881
    high_bound: 6891
  register: port_lookup_6881
  ignore_errors: true

- name: Pre-Install | Settings | Update settings For Existing Installs
  ansible.builtin.import_tasks: "existing_installs.yml"
  when: rutorrent_paths_rtorrent_rc_location_stat.stat.exists
