#########################################################################
# Title:         Bizbox: DNS | Cloudflare | Add DNS Record             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Add DNS Record | Remove DNS CNAME Record
  community.general.cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ dns_zone }}"
    state: absent
    type: CNAME
    record: "{{ dns_record }}"
  register: cloudflare_dns_record_removal_status

- name: Cloudflare | Add DNS Record | Tasks on success
  block:

    - name: Cloudflare | Add DNS Record | Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

    - name: Cloudflare | Add DNS Record | Display DNS CNAME Record removal status
      ansible.builtin.debug:
        msg: "DNS CNAME Record for '{{ dns_record_print }}' was removed."

  when: cloudflare_dns_record_removal_status is succeeded and cloudflare_dns_record_removal_status.changed

- name: Cloudflare | Add DNS Record | IPv4 Block
  block:

    - name: Cloudflare | Validate IP variable
      ansible.builtin.fail:
        msg: "ip_address_public contains: '{{ ip_address_public }}' which is not a valid IP"
      when: not ip_address_public_is_valid

    - name: Cloudflare | Add DNS Record | Add DNS Record
      community.general.cloudflare_dns:
        account_api_token: "{{ cloudflare.api }}"
        account_email: "{{ cloudflare.email }}"
        zone: "{{ dns_zone }}"
        state: present
        solo: true
        proxied: "{{ dns_proxy }}"
        type: A
        value: "{{ ip_address_public }}"
        record: "{{ dns_record }}"
      register: cloudflare_dns_record_creation_status

    - name: Cloudflare | Add DNS Record | Tasks on success
      block:

        - name: Cloudflare | Add DNS Record | Set 'dns_record_print' variable
          ansible.builtin.set_fact:
            dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

        - name: Cloudflare | Add DNS Record | Display DNS Record creation status
          ansible.builtin.debug:
            msg: "DNS A Record for '{{ dns_record_print }}' set to '{{ ip_address_public }}' was added. Proxy: {{ dns_proxy }}"

      when: cloudflare_dns_record_creation_status is succeeded

  when: dns.ipv4

- name: Cloudflare | Add DNS Record | IPv6 Block
  block:

    - name: Cloudflare | Validate IPv6 variable
      ansible.builtin.fail:
        msg: "ipv6_address_public contains: '{{ ipv6_address_public }}' which is not a valid IP"
      when: not ipv6_address_public_is_valid

    - name: Cloudflare | Add DNS Record | Add DNS Record
      community.general.cloudflare_dns:
        account_api_token: "{{ cloudflare.api }}"
        account_email: "{{ cloudflare.email }}"
        zone: "{{ dns_zone }}"
        state: present
        solo: true
        proxied: "{{ dns_proxy }}"
        type: AAAA
        value: "{{ ipv6_address_public }}"
        record: "{{ dns_record }}"
      register: cloudflare_dns_v6_record_creation_status

    - name: Cloudflare | Add DNS Record | Tasks on success
      block:

        - name: Cloudflare | Add DNS Record | Set 'dns_record_print' variable
          ansible.builtin.set_fact:
            dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

        - name: Cloudflare | Add DNS Record | Display DNS Record creation status
          ansible.builtin.debug:
            msg: "DNS AAAA Record for '{{ dns_record_print }}' set to '{{ ipv6_address_public }}' was added. Proxy: {{ dns_proxy }}"

      when: cloudflare_dns_v6_record_creation_status is succeeded

  when: dns.ipv6


- name: Cloudflare | Add DNS Record | IPv6 Block
  block:

    - name: Cloudflare | IPv6 | Add DNS Record | Remove unused AAAA DNS Record
      community.general.cloudflare_dns:
        account_api_token: "{{ cloudflare.api }}"
        account_email: "{{ cloudflare.email }}"
        zone: "{{ dns_zone }}"
        state: absent
        type: AAAA
        record: "{{ dns_record }}"
      register: cloudflare_dns_v6_record_removal_status

    - name: Cloudflare | IPv6 | Add DNS Record | Tasks on success
      block:

        - name: Cloudflare | IPv6 | Add DNS Record | Set 'dns_record_print' variable
          ansible.builtin.set_fact:
            dns_record_print: "{{ (dns_record == dns_zone) | ternary(dns_zone, dns_record + '.' + dns_zone) }}"

        - name: Cloudflare | IPv6 | Add DNS Record | Display DNS Record removal status
          ansible.builtin.debug:
            msg: "DNS AAAA Record for '{{ dns_record_print }}' was removed."

      when: cloudflare_dns_v6_record_removal_status is succeeded

  when: not dns.ipv6
