#########################################################################
# Title:         Bizbox: NZBGet | Post-Install Tasks                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config file to be created
  ansible.builtin.wait_for:
    path: "{{ nzbget_paths_config_location }}"
    state: present

- name: Post-Install | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Post-Install | Stop container
  community.docker.docker_container:
    name: "{{ nzbget_docker_container }}"
    state: stopped
    container_default_behavior: compatibility

- name: Post-Install | Scripts Task
  ansible.builtin.import_tasks: "scripts/main.yml"

- name: Post-Install | Settings Task
  ansible.builtin.import_tasks: "settings/main.yml"

- name: Post-Install | Start container
  community.docker.docker_container:
    name: "{{ nzbget_docker_container }}"
    state: "{{ nzbget_docker_state }}"
    container_default_behavior: compatibility
