#########################################################################
# Title:         Bizbox: yyq Role | Defaults Variables                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/GrecoTechnology/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
yyq_install_version: "4.31.1"
