############################################################################
# Title:            Bizbox: Wordpress | Configure HTTP Headers             #
# Author(s):        btmarouane                                             #
# URL:              https://github.com/GrecoTechnology/Bizbox              #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Copy http_headers.yml file
  template:
    src: "{{http_headers_tamplate}}"
    dest: "{{traefik_path_http_headers_config_location}}/{{role_name}}-http-headers.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: Create http_headers.yml symbolic link
  ansible.builtin.file:
    src: "{{traefik_path_http_headers_config_location}}/{{user.domain}}-{{role_name}}-http-headers.yml"
    dest: "{{role_config_path}}/http_headers.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    follow: false
    state: link
