#########################################################################
# Title:         Bizbox: Plex | Pre-Install Tasks                      #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Get next available port within the range of '32400-32410' # noqa fqcn[action]
  find_next_open_port:
    low_bound: 32400
    high_bound: 32410
  register: port_lookup_32400
  ignore_errors: true

- name: Pre-Install | Import Modify Binary'
  ansible.builtin.import_tasks: modify_binary.yml
  when: plex_modify_binary
