#########################################################################
# Title:         Bizbox: Kernel | Cron Tasks                           #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cron | Install cron
  ansible.builtin.apt:
    name: cron
    state: present

- name: Cron | Purge old kernels on reboot
  ansible.builtin.cron:
    name: "Remove old kernels on reboot"
    special_time: reboot
    job: "{{ kernel_cron_task }}"
