##########################################################################
# Title:         Bizbox: Authelia | Settings Task                       #
# Author(s):     salty                                                   #
# URL:           https://github.com/jeremiahg7/Bizbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Load encryption_key value
  ansible.builtin.shell: |
    yyq e '.storage.encryption_key' {{ authelia_paths_location }}/configuration.yml
  register: authelia_encryption_key

- name: Add encryption_key to config file
  ansible.builtin.shell: |
    yyq e -i '.storage.encryption_key = "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"' {{ authelia_paths_location }}/configuration.yml
  become: true
  become_user: "{{ user.name }}"
  when: authelia_encryption_key.stdout == "null"
