#########################################################################
# Title:         Bizbox: ruTorrent | Post-Install Tasks                #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config files to be created
  ansible.builtin.wait_for:
    path: "{{ item }}"
    state: present
  loop:
    - "{{ rutorrent_paths_rtorrent_rc_location }}"
    - "{{ rutorrent_paths_nginx_conf_location }}"
    - "{{ rutorrent_paths_php_local_ini_location }}"
    - "{{ rutorrent_paths_plugins_ini_location }}"

- name: Post-Install | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Post-Install | Stop container
  community.docker.docker_container:
    name: "{{ rutorrent_docker_container }}"
    container_default_behavior: compatibility
    tls_hostname: localhost
    state: stopped

- name: Post-Install | Settings Task
  ansible.builtin.import_tasks: "settings/main.yml"

- name: Post-Install | Start container
  community.docker.docker_container:
    name: "{{ rutorrent_docker_container }}"
    container_default_behavior: compatibility
    tls_hostname: localhost
    state: "{{ rutorrent_docker_state }}"
