#########################################################################
# Title:         Bizbox: Notify Role                                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import Variables Task
  ansible.builtin.import_tasks: "subtasks/variables.yml"

- name: Sent Notification
  ansible.builtin.include_tasks: "subtasks/{{ item }}.yml"
  loop: "{{ notification_services }}"
