##########################################################################
# Title:         Bizbox: TraefikAurh | Default Variables                 #
# Author(s):     btmarouane                                              #
# URL:           https://github.com/GrecoTechnology/Bizbox               #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

traefikauth_name: "{{ user.domain | replace('.','-')+'-traefikauth' }}"

################################
# Config
################################

################################
# Paths
################################

traefikauth_paths_folder: traefikauth
traefikauth_paths_location: "{{ server_appdata_path }}/{{ traefikauth_paths_folder }}"
traefikauth_config_path: "{{ traefikauth_paths_location }}/config"
traefikauth_data_path: "{{ traefikauth_paths_location }}/_data"
traefikauth_env_path: "{{ traefikauth_config_path }}/traefikauth.env.yml"
traefikauth_paths_folders_list:
  - "{{ traefikauth_paths_location }}"
  - "{{ traefikauth_config_path }}"
  - "{{ traefikauth_data_path }}"

################################
# Web
################################

traefikauth_web_subdomain: "traefikauth"
traefikauth_web_domain: "{{ user.domain }}"
traefikauth_web_port: "80"
traefikauth_web_url: "{{ 'https://' + traefikauth_web_subdomain + '.' + traefikauth_web_domain
                    if (reverse_proxy_is_enabled)
                    else 'http://localhost:' + traefikauth_web_port }}"

################################
# DNS
################################

traefikauth_dns_record: "{{ traefikauth_web_subdomain }}"
traefikauth_dns_zone: "{{ traefikauth_web_domain }}"
traefikauth_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

traefikauth_traefik_middleware: "{{ traefikauth_name +'@file' +','+ traefik_default_middleware }}"
traefikauth_traefik_certresolver: "{{ traefik_default_certresolver }}"
traefikauth_traefik_enabled: true

################################
# Docker
################################

# Container
traefikauth_docker_container: "{{ traefikauth_name }}"

# Image
traefikauth_docker_image_pull: true
traefikauth_docker_image_tag: "2"
traefikauth_docker_image: "thomseddon/traefik-forward-auth:{{ traefik_docker_image_tag }}"

# Ports
traefikauth_docker_ports_defaults:
  - "{{ traefikauth_web_port }}"
traefikauth_docker_ports_custom: []
traefikauth_docker_ports: "{{ traefikauth_docker_ports_defaults
                            + traefikauth_docker_ports_custom
                         if (not reverse_proxy_is_enabled)
                         else traefikauth_docker_ports_custom }}"
# Envs
traefikauth_docker_envs_default:
  DEFAULT_PROVIDER: "oidc"
  LOG_LEVEL: "trace"

traefikauth_docker_envs_custom: "{{ (lookup('file', server_domain_env_path) | from_yaml ).traefikauth }}"
traefikauth_docker_envs: "{{ traefikauth_docker_envs_default
                           | combine(traefikauth_docker_envs_custom) }}"

# Commands
traefikauth_docker_commands_default: []
traefikauth_docker_commands_custom: []
traefikauth_docker_commands: "{{ traefikauth_docker_commands_default
                               + traefikauth_docker_commands_custom }}"

# Volumes
traefikauth_docker_volumes_default: []
traefikauth_docker_volumes_custom: []
traefikauth_docker_volumes: "{{ traefikauth_docker_volumes_default
                              + traefikauth_docker_volumes_custom }}"

# Devices
traefikauth_docker_devices_default: []
traefikauth_docker_devices_custom: []
traefikauth_docker_devices: "{{ traefikauth_docker_devices_default
                              + traefikauth_docker_devices_custom }}"

# Hosts
traefikauth_docker_hosts_default: []
traefikauth_docker_hosts_custom: []
traefikauth_docker_hosts: "{{ docker_hosts_common
                            | combine(traefikauth_docker_hosts_default)
                            | combine(traefikauth_docker_hosts_custom) }}"

# Labels
traefikauth_docker_labels_default: {}
traefikauth_docker_labels_custom: {}
traefikauth_docker_labels: "{{ docker_labels_common
                                  | combine(traefikauth_docker_labels_default)
                                  | combine(traefikauth_docker_labels_custom) }}"

# Hostname
traefikauth_docker_hostname: "{{ traefikauth_web_domain }}"

# Networks
traefikauth_docker_networks_alias: "{{ traefikauth_name }}"
traefikauth_docker_networks_default: []
traefikauth_docker_networks_custom: []
traefikauth_docker_networks: "{{ docker_networks_common
                               + traefikauth_docker_networks_default
                               + traefikauth_docker_networks_custom }}"

# Capabilities
traefikauth_docker_capabilities_default: []
traefikauth_docker_capabilities_custom: []
traefikauth_docker_capabilities: "{{ traefikauth_docker_capabilities_default
                                   + traefikauth_docker_capabilities_custom }}"

# Security Opts
traefikauth_docker_security_opts_default: []
traefikauth_docker_security_opts_custom: []
traefikauth_docker_security_opts: "{{ traefikauth_docker_security_opts_default
                                    + traefikauth_docker_security_opts_custom }}"

# Restart Policy
traefikauth_docker_restart_policy: unless-stopped

# State
traefikauth_docker_state: started
