#########################################################################
# Title:         Bizbox: Traefik | Config Task                          #
# Author(s):     RXWatcher, salty                                       #
# URL:           https://github.com/GrecoTechnology/Bizbox              #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove 'themepark.yml'
  ansible.builtin.file:
    path: "{{ traefik_paths_location }}/themepark.yml"
    state: absent

- name: Create auth file
  community.general.htpasswd:
    path: /opt/traefik/auth
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"

- name: "Import 'dynamic.yml'"
  ansible.builtin.template:
    src: dynamic-default.yml.j2
    dest: /opt/traefik/config/dynamic-default.yml
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
