#########################################################################
# Title:         Bizbox: Traefik | Config Task                         #
# Author(s):     RXWatcher, salty                                       #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Import 'dynamic.yml'"
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: "{{ traefik_paths_location }}/dynamic.yml"
    force: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: Remove 'themepark.yml'
  ansible.builtin.file:
    path: "{{ traefik_paths_location }}/themepark.yml"
    state: absent

- name: Create auth file
  community.general.htpasswd:
    path: /opt/traefik/auth
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
