#########################################################################
# Title:         Bizbox: Traefik | ZeroSSL Task                        #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get new credentials
  ansible.builtin.uri:
    url: https://api.zerossl.com/acme/eab-credentials-email
    method: POST
    body:
      email: "{{ user.email }}"
    body_format: form-urlencoded
    return_content: true
  register: zerossl

- name: "Set ZeroSSL variables"
  ansible.builtin.set_fact:
    traefik_zerossl_kid: "{{ zerossl.json.eab_kid }}"
    traefik_zerossl_hmacencoded: "{{ zerossl.json.eab_hmac_key }}"
  when: (zerossl.status == 200) and zerossl.json.success

- name: "Fail when unable to get new credentials"
  ansible.builtin.fail:
    msg: Failed to retrieve ZeroSSL credentials.
  when: (zerossl.status != 200) or (not zerossl.json.success)
