##########################################################################
# Title:         Bizbox  | Reinstall                                     #
# Author(s):     btmarouane                                              #
# URL:           https://github.com/GrecoTechnology/Bizbox               #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Get list of apps' subfolders
  block:
  - name: Get list of apps' subfolders | Get apps
    ansible.builtin.find:
      paths: "{{ server_appdata_path }}"
      file_type: directory
      recurse: false
    register: apps

  - name: Set apps names
    set_fact:
      apps: "{{apps.files}}"
  when: all is defined and all == 'true'

- name: Set apps list
  block:
  - set_fact:
      apps_list: "{{ apps|map(attribute='path')|map('basename')|list }}"
    when: "apps | type_debug == 'list'"

  - debug:
      msg: "{{apps}}"

  - set_fact:
      apps_list: "{{ apps | split(',') }}"
    when: "apps | type_debug != 'list'"

  - debug:
      msg: "{{apps_list[0]}}"

  - set_fact:
      apps: "{{ [ 'traefik' ] + apps | reject('equalto', 'traefik') | list }}"
    when: "'traefik' in apps"

- name: Reinstall apps
  include_tasks: subtasks/reinstall_app.yml
  with_items: "{{apps_list}}"
  loop_control:
    loop_var: app_item
