#########################################################################
# Title:         Bizbox: Start Services Task                           #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Start 'unionfs.service'
  ansible.builtin.systemd:
    state: started
    name: unionfs
    daemon_reload: true
    enabled: true
  when: unionfs_service.stat.exists and unionfs_service_running

- name: Start 'mergerfs.service'
  ansible.builtin.systemd:
    state: started
    name: mergerfs
    daemon_reload: true
    enabled: true
  when: mergerfs_service.stat.exists and mergerfs_service_running

- name: Wait for 30 seconds before commencing
  ansible.builtin.wait_for:
    timeout: 30
  when: (docker_binary.stat.exists) and (docker_service_running) and not (docker_running_containers.stdout | trim | length == 0)

- name: "Re-start all previously running Docker containers"
  ansible.builtin.shell: 'docker start {{ docker_running_containers.stdout }}'
  ignore_errors: true
  when: (docker_binary.stat.exists) and (docker_service_running) and not (docker_running_containers.stdout | trim | length == 0)
