############################################################################
# Title:            Bizbox: Reinstall | Reinstall apps Task                #
# Author(s):        btmarouane                                             #
# URL:              https://github.com/GrecoTechnology/Bizbox              #
# --                                                                       #
############################################################################
#                   GNU General Public License v3.0                        #
############################################################################
---
- name: Reinstall apps | Set app name
  set_fact:
    app: "{{ 'invoice' if app_item in ['invoiceninja', 'invoiceninjav5'] else app_item }}"

- name: Reinstall apps | Check role name
  stat:
    path: "{{ server_appdata_path }}/{{ app }}"
  register: register_role_name

- name: debug
  debug:
    msg: "force enabled"
  when: force is defined and force == 'true'

- name: Reinstall apps | Reinstall app
  block:
  - name: Reinstall apps | Reinstall app | Uninstall app
    ansible.builtin.import_tasks: "{{ uninstall_task_path }}"
    vars:
      app: "{{ app }}"
    when: force is defined and force == 'true'

  - name: Reinstall apps | Reinstall app | Install app
    ansible.builtin.include_role:
      name: "{{ 'invoiceninjav5' if app == 'invoice' else app }}"
  when: register_role_name.stat.exists and app not in util_apps
