#########################################################################
# Title:         Bizbox: NZBGet | Post-Install | Scripts Task          #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Scripts | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ nzbget_scripts_paths_folders_list }}"

# Add Scripts

- name: Post-Install | Scripts | Download scripts repos
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ nzbget_scripts_paths_location }}/{{ (item | basename | splitext)[0] }}"
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ nzbget_scripts_repos_list }}"
  ignore_errors: true

- name: Post-Install | Scripts | Download script URLs
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ nzbget_scripts_paths_location }}"
    validate_certs: false
    force: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  loop: "{{ nzbget_scripts_direct_downloads_list }}"
  ignore_errors: true

- name: Post-Install | Scripts | Import local scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nzbget_scripts_paths_location }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
    force: true
  loop: "{{ nzbget_scripts_local_copy_list }}"

# Customize Scripts

- name: Post-Install | Scripts | Check if 'nzbgetpp/rarfile/rarfile.py' exists
  ansible.builtin.stat:
    path: "{{ nzbget_scripts_paths_rarfile_py_location }}"
  register: nzbget_scripts_rarfile_py_stat

- name: Post-Install | Scripts | Add unrar path to 'nzbgetpp/rarfile/rarfile.py'
  ansible.builtin.lineinfile:
    path: "{{ nzbget_scripts_paths_rarfile_py_location }}"
    regexp: '^UNRAR_TOOL\s?=.*'
    line: 'UNRAR_TOOL = "/app/unrar"'
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: nzbget_scripts_rarfile_py_stat.stat.exists
