#########################################################################
# Title:         Bizbox: Settings | Main 2                             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Settings | Copy"
  ansible.builtin.include_tasks: "subtasks/copy.yml"
  vars:
    file: "{{ outer_item }}"

- name: "Settings | Migrator"
  ansible.builtin.include_tasks: "subtasks/migrator.yml"
  vars:
    file: "{{ outer_item }}"

- name: "Settings | Updater"
  ansible.builtin.include_tasks: "subtasks/updater.yml"
  vars:
    file: "{{ outer_item }}"
  when: (outer_item != "ansible.cfg")
