##########################################################################
# Title:         Bizbox: Plex Extra Tasks | Post-Install Checks         #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/jeremiahg7/Bizbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Post-Install Checks | Wait for '{{ plex_paths_config_location | basename }}' to be created
  ansible.builtin.wait_for:
    path: "{{ plex_paths_config_location }}"
    state: present

- name: Post-Install Checks | Wait for {{ plex_name | title }} DB to be created
  ansible.builtin.wait_for:
    path: "{{ plex_paths_db_location }}"
    state: present

- name: Post-Install Checks | Wait for {{ plex_name | title }} executable to be created
  community.docker.docker_container_exec:
    container: "{{ plex_docker_container }}"
    command: bash -c "ls '/usr/lib/plexmediaserver/Plex Media Server'"
  register: pms_check
  until: pms_check.stderr.find("No such file or directory") == -1
  retries: 600
  changed_when: false
  failed_when: pms_check.rc == 1 or pms_check.rc > 2
