#########################################################################
# Title:         Bizbox: Settings | Finish                             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Finish | Check 'settings-updater.py' for new settings"
  ansible.builtin.debug: # noqa jinja[invalid]
    msg:
      - "The 'settings_updater.py' script updated the following
          file{{ 's' if (files_updated_successfully | length > 1) else '' }}: '{{ files_updated_successfully | difference(['ansible.cfg']) | join(', ') | trim }}'"
      - "Please check {{ 'these files' if (files_updated_successfully | length > 1) else 'this file' }} for the newly added settings"
      - "You can also review the log file: 'settings-updater.log'"
  when:
    - files_updated_successfully | difference(['ansible.cfg']) | length > 0

# Exit playbook When necessary
- name: Finish | Exit Tasks
  block:

    - name: "Finish | Check 'settings-updater.py' run status for errors"
      ansible.builtin.debug:
        msg:
          - "The 'settings_updater.py' script exited with an error when updating the following
              file{{ 's' if (files_updated_unsuccessfully | length > 1) else '' }}: '{{ files_updated_unsuccessfully | join(', ') | trim }}'"
          - "Please check 'settings-updater.log' for details"
      when: files_updated_unsuccessfully | length > 0

    - name: "Finish | 'ansible.cfg' was updated."
      ansible.builtin.debug:
        msg:
          - "Settings Role updated 'ansible.cfg'"
          - "You will need to re-run your previous tag."
      when: ('ansible.cfg' in files_updated_successfully)

    - name: "Finish | Exit so that user can check updated config files"
      ansible.builtin.debug:
        msg: "Bizbox Installer will now exit."

    - name: "Finish | Exit"
      ansible.builtin.meta: end_play

  when: exit_is_necessary

# Make sure accounts.yml has been filled in by user
- name: "Finish | Get stats on 'accounts.yml' for hash check"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/accounts.yml"
  register: accounts_yml

- name: "Finish | Get stats on 'accounts.yml.default' for hash check"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/defaults/accounts.yml.default"
  register: accounts_yml_default

# Sanity Checks
- name: "Finish | Ensure that 'accounts.yml' is configured"
  ansible.builtin.assert:
    that:
      - accounts_yml.stat.exists
      - accounts_yml.stat.checksum != accounts_yml_default.stat.checksum
    msg: "You must configure 'accounts.yml' before running the Bizbox installer"
