#########################################################################
# Title:         Bizbox: Plex Role                                     #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Plex roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    plex_name: "{{ role }}"
  with_items: "{{ plex_instances }}"
  loop_control:
    loop_var: role
