#########################################################################
# Title:         Bizbox: Bizbox_mod Role                              #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create bizbox_mod directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: true
  with_items:
    - /opt/bizbox_mod

- name: Clone bizbox_mod repo
  ansible.builtin.git:
    repo: "{{ bizbox_mod_repo }}"
    dest: /opt/bizbox_mod
    clone: true
    version: "{{ bizbox_mod_branch }}"
    force: "{{ bizbox_mod_force_overwrite }}"
  become: true
  become_user: "{{ user.name }}"
  ignore_errors: true
