##########################################################################
# Title:         Bizbox: UnionFS | Default Variables                    #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/jeremiahg7/Bizbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Global
################################

local_mount_branch: "{{ '/mnt/feeder' if (feeder_remote_is_active is defined and feeder_remote_is_active) else '/mnt/local' }}"

mount_type: "mergerfs"

################################
# MergerFS
################################

mergerfs_version: latest

mergerfs_github_endpoint: "{{ 'latest' if (mergerfs_version == 'latest') else 'tags/' + mergerfs_version }}"

mergerfs_releases_url: "{{ cvm }}https://api.github.com/repos/trapexit/mergerfs/releases/{{ mergerfs_github_endpoint }}"

mergerfs_releases_download_url: https://github.com/trapexit/mergerfs/releases/download

mergerfs_release_distribution: "{{ ansible_distribution_release | lower }}"

mergerfs_release_lookup_command: |
  curl -s {{ mergerfs_releases_url }} \
    | jq -r ".assets[] | select(.name | test(\"{{ ansible_distribution | lower }}-{{ mergerfs_release_distribution }}_amd64\")) \
    | .browser_download_url"

mergerfs_download_backup_version: 2.33.5

mergerfs_download_backup_url: "
  {{ mergerfs_releases_download_url }}/\
  {{ mergerfs_download_backup_version }}/\
  mergerfs_{{ mergerfs_download_backup_version }}.\
  {{ ansible_distribution | lower }}-\
  {{ mergerfs_release_distribution }}_amd64.deb"

mergerfs_mount_branches: "{{ local_mount_branch }}=RW:/mnt/remote=NC"

mergerfs_mount_service_after: "network-online.target"

mergerfs_mount_start_command: |-
  /usr/bin/mergerfs \
    -o category.create=ff,async_read=true,cache.files=partial \
    -o dropcacheonclose=true,use_ino,minfreespace=0 \
    -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime \
    {{ mergerfs_mount_branches }} /mnt/unionfs

mergerfs_mount_stop_command: /bin/fusermount -u /mnt/unionfs
