####################################################################################
# Title:         Bizbox: qBittorrent | Post-Install | Settings                    #
# Author(s):     salty                                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                               #
# --                                                                               #
####################################################################################
#                   GNU General Public License v3.0                                #
####################################################################################
---
- name: Post-Install | Settings | Update Port in 'qBittorrent.conf' config settings
  community.general.ini_file:
    path: "{{ qbittorrent_paths_conf }}"
    section: BitTorrent
    option: Session\Port
    value: "{{ qbittorrent_docker_ports_56881 }}"
    no_extra_spaces: true
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: Post-Install | Settings | Update HostHeaderValidation 'qBittorrent.conf' config settings
  community.general.ini_file:
    path: "{{ qbittorrent_paths_conf }}"
    section: Preferences
    option: WebUI\HostHeaderValidation
    value: "false"
    no_extra_spaces: true
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"

- name: Post-Install | Settings | Update CSRFProtection 'qBittorrent.conf' config settings
  community.general.ini_file:
    path: "{{ qbittorrent_paths_conf }}"
    section: Preferences
    option: WebUI\CSRFProtection
    value: "false"
    no_extra_spaces: true
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
