#########################################################################
# Title:         Bizbox: Cloudflare | Page Rules Task                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Delete any existing CF Page Rules for Lets Encrypt

- name: Page Rules | Remove Page Rule Task
  ansible.builtin.import_tasks: "page_rules/remove_page_rule.yml"
  when: (cloudflare_page_rules | length > 0)

# Create new CF Page Rule for Lets Encrypt

- name: Page Rules | Add Page Rule Task
  ansible.builtin.import_tasks: "page_rules/add_page_rule.yml"
