#########################################################################
# Title:         Bizbox: Mainline Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Bizbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install gnupg Dependencies
  ansible.builtin.apt:
    name: dirmngr

- name: Add cappelikan apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3AE27527713D2479DCAFFD58A89D7C1B2F76304D
    keyring: /usr/share/keyrings/cappelikan.gpg

- name: Add cappelikan/ppa repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/cappelikan.gpg] http://ppa.launchpad.net/cappelikan/ppa/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: "cappelikan"
    state: present
    update_cache: true

- name: Install mainline
  ansible.builtin.apt:
    name: mainline
    state: present
